import { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, Bot, BrainCircuit, CheckCircle2, GitBranch, Network, RefreshCw, Shield, Sparkles, Timer, UserCheck, Zap } from 'lucide-react'

type Timeline={id?:string;source:string;severity:string;timestamp:string;entity_id?:string;entity_name?:string;type:string;summary:string;replayed:boolean;correlation_id?:string;stage?:string;action?:string;outcome?:string}
type Component={entity_id:string;name:string;namespace:string;entity_type:string;risk:number;security_posture:string;fragility:number;finding_count:number}
type Overview={generated_at:string;status:string;fleet_risk:number;risk_level:string;counts:Record<string,number>;sources:Record<string,{connected:boolean;findings:number}>;components:Component[];timeline:Timeline[];topology:{nodes:any[];edges:any[]};trust:any[]}
const API='/api', palette={argus:'#45d9ff',phoenix:'#b68cff',sentinel:'#54efa9',human:'#ffd166',critical:'#ff5874',high:'#ffad55',medium:'#f2d65c',low:'#55e6a5',info:'#6594cc'} as const
const color=(s:string)=>palette[s as keyof typeof palette]||palette.info
const age=(v?:string)=>{if(!v)return'unknown';const n=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/1000));return n<60?`${n}s ago`:n<3600?`${Math.floor(n/60)}m ago`:`${Math.floor(n/3600)}h ago`}

function PanelTitle({kicker,title,help,right}:{kicker:string;title:string;help:string;right?:string}){return <div className="panel-title"><div><span>{kicker}</span><h3>{title}</h3><p>{help}</p></div>{right&&<small>{right}</small>}</div>}
function Stat({label,value,sub,icon:Icon,colorName}:{label:string;value:string|number;sub:string;icon:any;colorName:string}){return <div className="stat" style={{color:color(colorName)}}><div><span>{label}</span><Icon size={14}/></div><b>{value}</b><small>{sub}</small></div>}

function CausalFlow({events}:{events:Timeline[]}){
 const top=events.filter(e=>e.source==='argus'||e.source==='phoenix').slice(0,5), stages=['Signal','Reason','Decision','Action','Outcome']
 const values=(e:Timeline)=>[e.entity_name||e.type,e.summary,e.stage||null,e.action||null,e.outcome||null]
 return <div className="causal-wrap"><div className="flow-head"><span>Agent</span>{stages.map((s,i)=><span key={s}><b>0{i+1}</b>{s}</span>)}</div>
  {top.length?top.map((e,i)=><div className={`flow-row ${e.replayed?'is-replay':'is-live'}`} key={e.id||i}><div className="agent-label" style={{color:color(e.source)}}>{e.source==='argus'?<Shield/>:e.source==='phoenix'?<Zap/>:<Bot/>}<span>{e.source}</span><small>{e.replayed?'REPLAY':'LIVE'} · {age(e.timestamp)}</small></div>{values(e).map((v,j)=><div className={`flow-node stage-${j} ${v?'':'missing'}`} key={j} title={v||'This stage has not been published'}><i style={{background:v?color(j===0?e.severity:e.source):undefined}}/>{j>0&&<svg><line x1="0" y1="18" x2="100%" y2="18"/></svg>}<b>{v||'Awaiting evidence'}</b><small>{j===0?e.severity:j===1?'agent assessment':j===2?'reasoning / policy':j===3?'bounded execution':'verified state'}</small></div>)}</div>):<Empty text="No correlated agent evidence yet. The flow will populate as Argus and Phoenix publish findings."/>}
  <div className="legend"><span><i className="real"/>live evidence</span><span><i className="replay"/>synthetic / replay</span><span>Read left → right: signal becomes a verified outcome</span></div></div>
}

function RiskMatrix({items,onSelect}:{items:Component[];onSelect:(c:Component)=>void}){
 const shown=items.slice(0,18);return <div className="matrix"><div className="y-title">Operational fragility ↑</div><div className="matrix-zone z1">COMPROMISED<br/>BUT RESILIENT</div><div className="matrix-zone z2">SYSTEMIC<br/>DANGER</div><div className="matrix-zone z3">HEALTHY<br/>ZONE</div><div className="matrix-zone z4">FRAGILE<br/>FOUNDATION</div>
 <svg viewBox="0 0 640 330" role="img" aria-label="Security exposure versus operational fragility risk matrix"><line className="axis" x1="42" y1="288" x2="620" y2="288"/><line className="axis" x1="42" y1="288" x2="42" y2="16"/><line className="mid" x1="331" y1="16" x2="331" y2="288"/><line className="mid" x1="42" y1="152" x2="620" y2="152"/>{shown.map((c,i)=>{const x=52+(c.risk/100)*555,y=280-(c.fragility/100)*255,r=7+Math.min(13,c.finding_count*1.8);return <g className="bubble" key={c.entity_id} onClick={()=>onSelect(c)}><circle cx={x} cy={y} r={r+5} fill={color(c.risk>=75?'critical':c.risk>=50?'high':c.risk>=25?'medium':'low')} opacity=".12"/><circle cx={x} cy={y} r={r} fill={color(c.risk>=75?'critical':c.risk>=50?'high':c.risk>=25?'medium':'low')} opacity=".82"/><text x={x+r+5} y={y+3}>{c.name.slice(0,16)}</text><title>{c.name}: exposure {c.risk}, fragility {c.fragility}, {c.finding_count} findings</title></g>})}<text className="axis-label" x="330" y="323">Security exposure →</text></svg>
 <div className="matrix-key"><span>Bubble size = findings</span><span>Click any service for evidence</span></div></div>
}

function TopologyGraph({nodes,edges,selected}:{nodes:any[];edges:any[];selected?:string}){
 const degrees=new Map<string,number>();edges.forEach(e=>{degrees.set(e.source_id,(degrees.get(e.source_id)||0)+1);degrees.set(e.target_id,(degrees.get(e.target_id)||0)+1)})
 const ns=[...nodes].sort((a,b)=>(b.entity_id===selected?1:0)-(a.entity_id===selected?1:0)||(degrees.get(b.entity_id)||0)-(degrees.get(a.entity_id)||0)||Number(b.fragility_score||0)-Number(a.fragility_score||0)).slice(0,22), W=660,H=330,cx=W/2,cy=H/2
 const pos=new Map(ns.map((n,i)=>[n.entity_id,{x:cx+Math.cos((i/ns.length)*Math.PI*2)*(105+(i%3)*47),y:cy+Math.sin((i/ns.length)*Math.PI*2)*(73+(i%3)*31)}]));const visibleEdges=edges.filter(e=>pos.has(e.source_id)&&pos.has(e.target_id)).slice(0,60)
 return <div className="graph">{ns.length?<svg viewBox={`0 0 ${W} ${H}`}>{visibleEdges.map((e,i)=>{const a=pos.get(e.source_id)!,b=pos.get(e.target_id)!;return <g key={i}><line className="edge" x1={a.x} y1={a.y} x2={b.x} y2={b.y}/><title>{e.edge_type||'depends on'}</title></g>})}{ns.map(n=>{const p=pos.get(n.entity_id)!,active=n.entity_id===selected,c=color(n.security_posture==='critical'?'critical':n.security_posture==='high-risk'?'high':n.fragility_score>.5?'medium':'low');return <g key={n.entity_id} className={`graph-node ${active?'selected':''}`}><circle cx={p.x} cy={p.y} r={active?16:9} fill={c}/><circle cx={p.x} cy={p.y} r={active?23:14} fill="none" stroke={c} opacity={.25+Number(n.fragility_score||0)*.7}/><text x={p.x+13} y={p.y+3}>{n.name.slice(0,12)}</text><title>{n.name}: {degrees.get(n.entity_id)||0} dependencies</title></g>})}</svg>:<Empty text="No topology entities have been published yet."/>}<div className="graph-legend"><span><i className="healthy"/>healthy</span><span><i className="warning"/>fragile</span><span><i className="danger"/>exposed</span><span>{visibleEdges.length} visible relationships</span><span>Halo intensity = fragility</span></div></div>
}

function TrustLadder({records}:{records:any[]}){return <div className="trust-list">{records.length?records.slice(0,6).map((r,i)=>{const total=(r.success_count||0)+(r.surprise_count||0),pct=total?Math.round((r.success_count/total)*100):0;return <div className="trust-row" key={r.action_type||i}><div><b>{r.action_type}</b><small>{r.state==='auto'?'Autonomous after verified outcomes':'Human approval required'}</small></div><div className="ladder"><span>GATED</span><div><i style={{width:`${pct}%`}}/><em style={{left:`${Math.min(96,pct)}%`}}/></div><span>AUTO</span></div><strong className={r.state==='auto'?'auto':'gated'}>{r.state}</strong><small>{r.success_count||0} success · {r.surprise_count||0} surprise</small></div>}):<Empty text="No action trust history yet. New actions begin human-gated and earn autonomy through verified success."/>}<div className="trust-explain"><UserCheck size={14}/><span>A surprise or failed verification immediately moves an action back to human-gated.</span></div></div>}

export default function App(){
 const[data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[brief,setBrief]=useState(''),[briefing,setBriefing]=useState(false),[selected,setSelected]=useState<Component|null>(null)
 const load=async()=>{setLoading(true);try{const r=await fetch(`${API}/overview`);if(!r.ok)throw Error(await r.text());setData(await r.json());setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[])
 const ask=async()=>{setBriefing(true);try{const r=await fetch(`${API}/briefing`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{"question":"What requires operator attention right now?"}'}),j=await r.json();setBrief(j.briefing||j.detail)}finally{setBriefing(false)}}
 const trust=useMemo(()=>({auto:data?.trust.filter(x=>x.state==='auto').length||0,gated:data?.trust.filter(x=>x.state!=='auto').length||0}),[data])
 return <div className="shell"><header><div className="brand"><div className="mark"><Network/></div><div><h1>SENTINEL</h1><p>OPENAI-NATIVE AUTONOMOUS OPERATIONS</p></div></div><div className="header-state"><i className={error?'bad':''}/><div><b>{error?'DEGRADED':'WORLD MODEL LIVE'}</b><small>{data?age(data.generated_at):'connecting'}</small></div><button onClick={load} className={loading?'spin':''}><RefreshCw/></button></div></header><main>
 <section className="hero"><div><span>UNIFIED COMMAND CENTER</span><h2>See the incident. Understand the risk.<br/><em>Trust the response.</em></h2><p>One evidence-backed view of what Argus detected, what Phoenix restored, and why Sentinel allowed—or stopped—an autonomous action.</p></div><div className={`risk-orb ${data?.risk_level||'stable'}`}><small>FLEET RISK</small><b>{data?.fleet_risk??'—'}</b><span>{data?.risk_level||'connecting'}</span></div></section>
 {error&&<div className="error"><AlertTriangle/>{error}</div>}<section className="stats"><Stat label="ARGUS SECURITY" value={data?.counts.argus||0} sub={data?.sources.argus.connected?'live findings synchronized':'waiting for shared evidence'} icon={Shield} colorName={data?.sources.argus.connected?'argus':'info'}/><Stat label="PHOENIX RESILIENCE" value={data?.counts.phoenix||0} sub={data?.sources.phoenix.connected?'verified outcomes synchronized':'integration not reporting'} icon={Zap} colorName={data?.sources.phoenix.connected?'phoenix':'info'}/><Stat label="HIGH-URGENCY SIGNALS" value={(data?.counts.critical||0)+(data?.counts.high||0)} sub={`${data?.counts.critical||0} critical · ${data?.counts.high||0} high`} icon={Activity} colorName="high"/><Stat label="AUTONOMY EARNED" value={`${trust.auto}/${trust.auto+trust.gated||0}`} sub={`${trust.gated} actions remain human-gated`} icon={CheckCircle2} colorName="sentinel"/></section>
 <section className="panel causal"><PanelTitle kicker="01 · CAUSAL CANVAS" title="From signal to verified outcome" help="Follow each incident left to right. Missing stages stay visible so an incomplete evidence chain cannot look resolved." right={`${data?.timeline.filter(e=>e.source==='argus'||e.source==='phoenix').length||0} agent events`}/><CausalFlow events={data?.timeline||[]}/></section>
 <section className="viz-grid"><div className="panel"><PanelTitle kicker="02 · COMBINED RISK" title="Security × fragility matrix" help="The upper-right is the danger zone: exposed services that also fail easily."/><RiskMatrix items={data?.components||[]} onSelect={setSelected}/>{selected&&<div className="selection"><b>{selected.name}</b><span>{selected.namespace}</span><strong>risk {selected.risk}</strong><span>fragility {selected.fragility}</span><span>{selected.finding_count} findings</span></div>}</div><div className="panel"><PanelTitle kicker="03 · BLAST RADIUS" title="Operational dependency graph" help="Edges show dependency. Color shows security posture; halo shows fragility." right={`${data?.counts.entities||0} nodes · ${data?.counts.edges||0} edges`}/><TopologyGraph nodes={data?.topology.nodes||[]} edges={data?.topology.edges||[]} selected={selected?.entity_id}/></div></section>
 <section className="lower-grid"><div className="panel"><PanelTitle kicker="04 · HUMAN GOVERNANCE" title="Autonomy trust ladder" help="Actions move right only after verified success. Surprise returns control to a human."/><TrustLadder records={data?.trust||[]}/></div><div className="panel intelligence"><div className="brief-head"><div><BrainCircuit/></div><div><span>OPENAI EVIDENCE BRIEFING</span><h3>What needs attention now?</h3><p>Generated only from the live World Model.</p></div><button onClick={ask}><Sparkles/>{briefing?'Reasoning…':brief?'Refresh':'Generate'}</button></div>{brief?<pre>{brief}</pre>:<Empty text="Generate a concise operational explanation linked to the evidence above."/>}</div></section>
 </main><footer><span>SENTINEL PLATFORM</span><span><Shield/> ARGUS <Zap/> PHOENIX <GitBranch/> WORLD MODEL</span><span><Timer/> 15s live refresh</span></footer></div>
}
function Empty({text}:{text:string}){return <div className="empty"><Activity/><span>{text}</span></div>}
